# Copyright 2019-2022 CEA LIST
# SPDX-FileCopyrightText: 2019-2022 CEA LIST <gael.de-chalendar@cea.fr>
#
# SPDX-License-Identifier: MIT
ARG PYTHON_VERSION=3.8
ARG QT_VERSION=5.15
FROM aymara/lima-manylinux_2_28-qt${QT_VERSION}-python${PYTHON_VERSION}:latest
# as aymara_lima-manylinux_2_28-qt-python

# FROM quay.io/pypa/manylinux_2_28_x86_64

ARG LIMA_PYTHON_VERSION
ARG PYSIDE_VERSION="2"
ARG PYTHON_VERSION="3.8"
ARG PYTHON_SHORT_VERSION="cp38-cp38"
ARG PYTHON_WHEEL_VERSION="cp38-abi3"
# For python 3.7, it is 3.7.13
# For python 3.8, it is 3.8.12
ARG PYTHON_FULL_VERSION="3.8.12"
ENV DEBIAN_FRONTEND=noninteractive

RUN yum install -y wget gcc-toolset-10.x86_64 ninja-build libicu-devel.x86_64  "qt5-*.x86_64" qt5-devel.noarch \
    clang.x86_64 python3-clang.x86_64 llvm-devel.x86_64 clang-devel.x86_64 libxml2-devel.x86_64 libxslt-devel.x86_64 \
    python3-sphinx.noarch
RUN ln -s /usr/bin/uic-qt5 /usr/bin/uic && \
    ln -s /usr/bin/rcc-qt5 /usr/bin/rcc && \
    ln -s /usr/lib64/libclang.so.13 /usr/lib64/libclang.so.1

RUN python${PYTHON_VERSION} -m pip install scikit-build
ENV PATH="/opt/_internal/cpython-${PYTHON_FULL_VERSION}/bin:/opt/python/${PYTHON_SHORT_VERSION}/bin:${PATH}"

ENV NLTK_PTB_DP_FILE=/nltk_data/corpora/dependency_treebank/nltk-ptb.dp \
    LIMA_DISABLE_FSW_TESTING=true \
    LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS=true \
    LIMA_DIST=/opt/lima \
    LIMA_CONF=/opt/lima/share/config/lima \
    LIMA_RESOURCES=/opt/lima/share/apps/lima/resources \
    PATH=/opt/llvm/bin:/opt/lima/bin:${PATH} \
    LD_LIBRARY_PATH=/opt/lima/lib:/opt/lima/lib64:${LD_LIBRARY_PATH} \
    PYTHON_VERSION=$PYTHON_VERSION \
    PYTHON_SHORT_VERSION=$PYTHON_SHORT_VERSION \
    PYTHON_FULL_VERSION=$PYTHON_FULL_VERSION \
    PYTHON_WHEEL_VERSION=$PYTHON_WHEEL_VERSION \
    LIMA_PYTHON_VERSION=$LIMA_PYTHON_VERSION

# Build LIMA wheel
RUN install -d /lima-python/scripts
COPY scripts/linuxdeploy.py /lima-python/scripts
WORKDIR /lima-python
RUN install -d clib/lib
RUN install -d /lima-python/aymaralima
RUN cp -R /opt/lima/share/apps/lima/resources /lima-python/aymaralima
RUN install -d /lima-python/aymaralima/config
RUN cp -R /opt/lima/share/config/lima/* /lima-python/aymaralima/config
RUN python${PYTHON_VERSION} /lima-python/scripts/linuxdeploy.py /opt/lima/lib/liblima*.so -d clib -o clib/libs.json
RUN /usr/bin/strip --strip-unneeded clib/lib/*.so
COPY scripts tests utils bindings.h bindings.xml c2lc.txt CHANGES.md CMakeLists.txt deploy.sh LICENCE lima.h lima.cpp macros.h manageQt5.cmake MANIFEST.in python_env.sh README.md setup.py /lima-python/
RUN install -d /lima-python/aymara
COPY aymara/* /lima-python/aymara

RUN python${PYTHON_VERSION} setup.py bdist_wheel
ENV LD_LIBRARY_PATH=/lima-python/_skbuild/linux-x86_64-${PYTHON_VERSION}/cmake-build:$LD_LIBRARY_PATH
# RUN auditwheel show /lima-python/dist/aymara-${LIMA_PYTHON_VERSION}-${PYTHON_SHORT_VERSION}-linux_x86_64.whl
# RUN pip install auditwheel-symbols
# RUN auditwheel-symbols -m 2_28 /lima-python/dist/aymara-${LIMA_PYTHON_VERSION}-${PYTHON_SHORT_VERSION}-linux_x86_64.whl
RUN auditwheel repair --plat manylinux_2_28_x86_64 /lima-python/dist/aymara-${LIMA_PYTHON_VERSION}-${PYTHON_SHORT_VERSION}-linux_x86_64.whl
WORKDIR /lima-python/wheelhouse
RUN unzip aymara-${LIMA_PYTHON_VERSION}-${PYTHON_SHORT_VERSION}-manylinux_2_28_x86_64.whl
RUN rm -f aymara-${LIMA_PYTHON_VERSION}-${PYTHON_SHORT_VERSION}-manylinux_2_28_x86_64.whl
WORKDIR /lima-python/wheelhouse/aymaralima
RUN rm -f liblima-* libgomp* libQt* libboost* libicu* libfasttext-lima.so  libtensorflow-for-lima.so
WORKDIR /lima-python/wheelhouse
RUN sed -ie "s/cp37m/abi3/" aymara-${LIMA_PYTHON_VERSION}.dist-info/WHEEL
RUN zip aymara-${LIMA_PYTHON_VERSION}-${PYTHON_WHEEL_VERSION}-manylinux_2_28_x86_64.whl -r *
# RUN mv aymara-${LIMA_PYTHON_VERSION}-${PYTHON_SHORT_VERSION}-manylinux_2_28_x86_64.whl aymara-${LIMA_PYTHON_VERSION}-${PYTHON_WHEEL_VERSION}-manylinux_2_28_x86_64.whl
# WORKDIR /lima-python
#
# WORKDIR /
