import os
import sys

from skbuild import setup  # This line replaces 'from setuptools import setup'


def package_files(directory):
    paths = []
    for (path, directories, filenames) in os.walk(directory):
        for filename in filenames:
            paths.append(os.path.join(path, filename))
    return paths


#extra_files = package_files('config')
#extra_files += package_files('resources')
#print(extra_files, file=sys.stderr)

#extra_libs = package_files('clib')

setup(
    name='aymara',
    version='0.3.0',
    packages=['aymara'],
    install_requires=[
        'pyconll',
        'requests',
        'unix_ar',
        'tqdm',
        ],
    include_package_data=True,

    # A dictionary mapping package names to lists of glob patterns. For a complete description and examples, see the setuptools documentation section on Including Data Files. You do not need to use this option if you are using include_package_data, unless you need to add e.g. files that are generated by your setup script and build process. (And are therefore not in source control or are files that you don’t want to include in your source distribution.)
    #package_data={'aymara': extra_files},
    package_data={},

    # Dictionary mapping package names to lists of glob patterns that should be excluded from the package directories. You can use this to trim back any excess files included by include_package_data. For a complete description and examples, see the setuptools documentation section on Including Data Files.
    exclude_package_data={},

    # Sequence of (directory, files) pairs. Each (directory, files) pair in the sequence specifies the installation directory and the files to install there. More details in the Installing Additional Files section of the setuptools documentation.
    #data_files=[('aymara', extra_libs)],
    data_files=[],

    #    cmake_install_dir= 'aymara/',
    cmake_minimum_required_version='3.15',
    setup_requires=['cmake', ],
    cmake_args=['-DCMAKE_BUILD_TYPE=Release',
                '-DCMAKE_GENERATOR=Ninja',
                "-DPython3_INCLUDE_DIR=/opt/python/cp38-cp38/include/python3.8",
                '-DPython3_LIBRARY=/opt/python/cp38-cp38/lib/python3.8'],
    scripts=['aymara/lima_models.py'],
)
