on:
  push:
    branches:
    - port-to-qt6

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: 3.10
  PYTHON_SHORT_VERSION: cp310-cp310
  PYTHON_FULL_VERSION: 3.10.5
  QT_VERSION_MAJOR: 6
  QT_VERSION_MINOR: 3
  QT_VERSION_PATCH: 1
  QT_VERSION: 6.3
  QT_FULL_VERSION: 6.3.1


jobs:

  lima-python:
    name: "Build the lima-python image with Qt ${QT_VERSION} for python ${PYTHON_VERSION}"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Build image"
        run: cd ./continuous_integration && docker build --progress=plain --build-arg PYTHON_VERSION="${PYTHON_VERSION}" --build-arg PYTHON_SHORT_VERSION=${PYTHON_SHORT_VERSION} --build-arg PYTHON_FULL_VERSION=${PYTHON_FULL_VERSION} --build-arg LIMA_PYTHON_VERSION=${LIMA_PYTHON_VERSION} -t aymara/lima-qt${QT_VERSION}-python${PYTHON_VERSION}:latest .

      - name: "Push image"
        run: docker push aymara/lima-qt${QT_VERSION}-python${PYTHON_VERSION}:latest

